### ISSUE TITLE
healpix format beams support in telescope config file

### ISSUE THREAD

**Issue by saurabh-astro** [RadioAstronomySoftwareGroup/pyuvsim#316] opened 2020-07-28 18:31 UTC
The default angular interpolation is `az_za_rect_spline `, which does not work with beamfiles described in healpix. Specifying `interpolation_function: 'healpix_simple'` does not seem to work either since we can not pass the filename in dictionary mode, while the interpolation function needs to be passed to each beam ID.

**Comment by bhazelton** [comment] 2020-07-28 19:44
@saurabh-astro Thanks, we should fix this. 

FYI if you are using a HERA beam from a CST simulation, you should be aware that those come out natively in a regular Az/ZA grid. Turning them into Healpix beams involves interpolation which introduces errors. In simulation, we then have to do more interpolation to get the beam response in the direction of a source. It is much more accurate to interpolate the beams in from their native frame than to have 2 interpolation steps, as you will with Healpix HERA beams.

**Comment by saurabh-astro** [comment] 2020-07-29 03:10
Thanks for the suggestion @bhazelton. Will check the beam in native coordinates too.

**Comment by aelanman** [comment] 2020-07-29 17:03
I'm having trouble reproducing this error. For me, including `interpolation_function` in the telescope config file correctly sets the interpolation method. Setting them individually for each UVBeam isn't possible, because the parameter file is used to construct a BeamList instance and same interpolation function is assigned to all UVBeams in a given BeamList instance.

@saurabh-astro could you please say a little more about this particular beamfits file, and paste the telescope config file you're using? It's also possible that something else is resetting the interpolation_function after the BeamList is set up, but I haven't checked that yet.

**Comment by saurabh-astro** [comment] 2020-08-03 20:30
Here is the minimum working example that produces errors:

```beam_paths:
  0: "hera_pspec/hera_pspec/data/HERA_NF_dipole_power.beamfits"
interpolation_function: 'healpix_simple'
telescope_location: (-30.72152777777791, 21.428305555555557, 1073.0000000093132)
telescope_name: custom```

I am using the healpix beam in `hera_pspec` for testing. 

`pyuvsim.__version__ :1.2.1.dev22+g9b71214`

This is the error:

```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-90c9f51948f1> in <module>()
      1 PATH_pyuvsim='/lustre/aoc/projects/hera/ssingh/packages/config_files/obsparam_pyuvsim_hera.yaml'
----> 2 uvsim.run_uvsim(PATH_pyuvsim)

/lustre/aoc/projects/hera/ssingh/anaconda3/envs/hera_pspec/lib/python3.7/site-packages/pyuvsim-1.2.1.dev22+g9b71214-py3.7.egg/pyuvsim/uvsim.py in run_uvsim(params, return_uv, quiet)
    587 
    588     uv_out = run_uvdata_uvsim(
--> 589         input_uv, beam_list, beam_dict=beam_dict, catalog=skydata, quiet=quiet
    590     )
    591 

/lustre/aoc/projects/hera/ssingh/anaconda3/envs/hera_pspec/lib/python3.7/site-packages/pyuvsim-1.2.1.dev22+g9b71214-py3.7.egg/pyuvsim/uvsim.py in run_uvdata_uvsim(input_uv, beam_list, beam_dict, catalog, quiet)
    472             summed_task_dict[task.uvdata_index] = task
    473         if summed_task_dict[task.uvdata_index].visibility_vector is None:
--> 474             summed_task_dict[task.uvdata_index].visibility_vector = engine.make_visibility()
    475         else:
    476             summed_task_dict[task.uvdata_index].visibility_vector += engine.make_visibility()

/lustre/aoc/projects/hera/ssingh/anaconda3/envs/hera_pspec/lib/python3.7/site-packages/pyuvsim-1.2.1.dev22+g9b71214-py3.7.egg/pyuvsim/uvsim.py in make_visibility(self)
    185 
    186         if self.update_beams:
--> 187             self.apply_beam()
    188 
    189         pos_lmn = srcs.pos_lmn[..., srcs.above_horizon]

/lustre/aoc/projects/hera/ssingh/anaconda3/envs/hera_pspec/lib/python3.7/site-packages/pyuvsim-1.2.1.dev22+g9b71214-py3.7.egg/pyuvsim/uvsim.py in apply_beam(self)
    148         self.beam1_jones = baseline.antenna1.get_beam_jones(
    149             self.task.telescope, sources.alt_az[..., sources.above_horizon],
--> 150             self.task.freq, reuse_spline=self.reuse_spline
    151         )
    152 

/lustre/aoc/projects/hera/ssingh/anaconda3/envs/hera_pspec/lib/python3.7/site-packages/pyuvsim-1.2.1.dev22+g9b71214-py3.7.egg/pyuvsim/antenna.py in get_beam_jones(self, array, source_alt_az, frequency, reuse_spline, interpolation_function, freq_interp_kind)
     93         try:
     94             interp_data, interp_basis_vector = \
---> 95                 array.beam_list[self.beam_id].interp(**interp_kwargs)
     96         except TypeError as err:   # pragma: nocover
     97             raise TypeError(

/lustre/aoc/projects/hera/ssingh/anaconda3/envs/hera_pspec/lib/python3.7/site-packages/pyuvdata-2.0.3.dev170+g3ede5392-py3.7-linux-x86_64.egg/pyuvdata/uvbeam/uvbeam.py in interp(self, az_array, za_array, az_za_grid, healpix_nside, healpix_inds, freq_array, freq_interp_tol, polarizations, return_bandpass, reuse_spline, spline_opts, new_object, run_check, check_extra, run_check_acceptability)
   1804             freq_interp_kind=kind_use,
   1805             polarizations=polarizations,
-> 1806             **extra_keyword_dict,
   1807         )
   1808 

/lustre/aoc/projects/hera/ssingh/anaconda3/envs/hera_pspec/lib/python3.7/site-packages/pyuvdata-2.0.3.dev170+g3ede5392-py3.7-linux-x86_64.egg/pyuvdata/uvbeam/uvbeam.py in _interp_az_za_rect_spline(self, az_array, za_array, freq_array, freq_interp_kind, freq_interp_tol, polarizations, reuse_spline, spline_opts)
   1277         """
   1278         if self.pixel_coordinate_system != "az_za":
-> 1279             raise ValueError('pixel_coordinate_system must be "az_za"')
   1280 
   1281         if freq_array is not None:

ValueError: pixel_coordinate_system must be "az_za"```

**Comment by aelanman** [comment] 2020-08-04 16:10
@saurabh-astro pyuvsim needs the E-field beam, not the power beam, since it treats the RIME with full polarization.

I think I've found the issue in pyuvsim -- the get_beam_jones function defaults to using az_za_simple regardless of what the input beam has. I'll push a fix later today.

**Comment by saurabh-astro** [comment] 2020-08-04 19:54
Thanks @aelanman. It runs with E-field alt-az beam file.

**Comment by aelanman** [comment] 2020-08-04 20:03
@saurabh-astro That's interesting... i got the same error you got even after I switched in the E-field beam. I found a bug in get_beam_jones that overwrites the interpolation method.

**Comment by saurabh-astro** [comment] 2020-08-04 21:48
> @saurabh-astro That's interesting... i got the same error you got even after I switched in the E-field beam. I found a bug in get_beam_jones that overwrites the interpolation method.

Oh, I meant it runs fine when E-field beam file is gridded in alt-az and not healpix. I haven't tested the latter yet.

**Closed** 2020-08-26 18:13 UTC
